version: "3"

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: changeMe
      MYSQL_DATABASE: app
      MYSQL_USER: maria-user
      MYSQL_PASSWORD: changeMe
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data: