version: "3"

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure --advertise-addr 'localhost'
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - backend

  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - cockroachdb
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  cockroach-data:
